// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pidulggnlxvkdnlmakus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpZHVsZ2dubHh2a2RubG1ha3VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDE5NDcsImV4cCI6MjA1OTYxNzk0N30.iLROoB1rfm8TY6Km_V6hOhrSYrzagNAPGgHrVat_kXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);